version: '3.7'
services:
  postgres:
    image: postgis/postgis:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'

  graphql-engine:
    image: hasura/graphql-engine:latest
    depends_on:
      - 'postgres'
    restart: always
    expose:
      - "8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: '{
        "type":"RS256",
        "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com",
        "audience": "${PROJECT_ID}",
        "issuer": "https://securetoken.google.com/${PROJECT_ID}"
      }'
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'

  minio:
    image: minio/minio:latest
    entrypoint: sh
    command: -c '/opt/bin/minio server --console-address ":9001" --address :8484 /data'
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    expose:
      - ${MINIO_PORT}
      - "9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
        - /mnt/HC_Volume_19420880/minio:/data
        
  imageproxy:
    depends_on:
      - "minio"
      - "graphql-engine"
    image: 'willnorris/imageproxy:latest'
    entrypoint: /app/imageproxy -addr 0.0.0.0:8081 -cache /tmp/cache -verbose
    expose:
      - '8081'
    volumes:
      - /tmp:/tmp/cache

  file-upload:
    depends_on:
      - "minio"
      - "graphql-engine"
    build: ./upload-file
    volumes:
      - .:/usr/src/app/upload-file
    container_name: upload-file
    expose:
      - '3333'
    env_file: .env

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      "80:80"
  